= {product} - Hist칩rias de Usuario
Universidad Cat칩lica Boliviana. <teddy.aruquipa@ucb.edu.bo>
1.0.1
:product: BOT Empresa Lunvas.

## Introducci칩n
El present칠 documento tendr치 el detalle de todas las histor칤as de usuario para la construcci칩n de un BOT en la plataforma de
Telegram, el cu치l estar치 dirigido para la empresa Lunvas.

Se ha establecido que la funcionalidad m칤nima para la implementaci칩n ser치:

Para los clientes:

 1. Los clientes pueden ver informaci칩n de la empresa, como ser las sucursales disponibles.
 2. Los clientes pueden consultar los productos disponibles mediante el BOT.
 3. Los clientes pueden realizar una reserva de producto para recogerlo posteriormente.

Para el personal de la empresa:

 1. El personal de la empresa debe poder aprobar o negar las reservas de productos.
 2. El personal puede consultar un producto de otra sucursal diferente a la suya.
 3. El personal de la empresa podra a침adir o eliminar productos.

Para el Administrador de la empresa:

 1. El administrador de la empresa debe poder registrar y actualizar los productos.

## Hist칩rias de Usuario.

### 100 - Solicitud de reserva de productos.

*Autor*: Gutber Blanco Gomez

*Fecha*: 01/03/2022

*Prioridad*: ALTA

#### Descripci칩n
Un `Cliente` debe solicitar la reserva de productos por medio de la aplicaci칩n, para esto debe especificar el o los productos que desea adquirir, asi como el horario en el que se recoger치 la mercaderia. Una vez enviada su solicitud el `Personal de Metal Corp.` proceder치 a aprobar o negar la solicitud de reserva del cliente, en caso de que la `Solicitud` sea negada se debe agregar un detalle del porqu칠 se neg칩 dicha reserva. Adem치s el `BOT` debe llevar un control de:
 * El stock de los productos
 * El registro de reservas realizadas
 * El tiempo de duraci칩n de la reserva

La solicitud pasar치 pos los siguientes estados:

  * *SOLICITADO*: Cuando el cliente env칤a su solicitud de reserva al BOT y el BOT no la rechaza.
  * *NO V츼LIDO*: Cuando el cliente env칤a su solicitud de reserva al BOT e ingresa una cantidad mayor al stock disponible del producto seleccionado.
  * *APROBADO*: Solicitud de reserva aprobada por el personal de Metal Corp.
  * *RECHAZADO*: Solicitud de reserva negadda por el personal de Metal Corp.
  * *CANCELADA*: El cliente cancel칩 una solicitud de reserva APROBADA

El diagrama de estados para la `SOLICITUD` ser치:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> CANCELADO
APROBADO --> [*]
CANCELADO --> [*]

@enduml
....

#### Escenarios
1. El producto no est치 registrado en la aplicaci칩n.
2. El producto est치 registrado en la aplicaci칩n con stock suficiente.
3. El producto est치 registrado en la aplicaci칩n con stock insuficiente.
4. Solicitud de reserva.
5. Cancelaci칩n de reserva.

#### Casos de Prueba

*100.1.1 Validaci칩n de la cantidad*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot pedir치 una cantidad el cual debe ser ingresado por el cliente.

En caso de que el `cliente ingrese una cantidad erronea` no se debe proceder a registrar el producto.

Pasos:

1. El `Cliente` env칤a el comando `/reservar (codigo)`
- Datos: comando `/reservar ####`
- Resultado: El BOT pregunta por la cantidad que requiere
2. El `Cliente` ingresa el n칰mero 0.
- Datos: Ingresa `0`
- Resultado: El BOT indica que el n칰mero no puede ser 0 o negativo
3. El `Cliente` coloca una cantidad mayor al stock.
- Datos: Ingresa `Cantidad mayor al stock`
- Resultado: El BOT le indica que la cantidad no puede superar al stock.


### 101 - Registro de producto en el sistema.

*Autor*: Teddy Aruquipa Peralta

*Fecha*: 03/03/2022

*Prioridad*: ALTA

#### Descripci칩n

El `Administrador de Metal Corp.` debe poder realizar el registro de nuevos productos en el sistema por medio del mismo BOT, al momento de solicitar su registro, el Administrador deber치 enviar la siguiente informaci칩n:

 * Nombre del producto.
 * Categor칤a.
 * C칩digo.
 * Foto del producto.
 * Cantidad disponible.
 * Dimensiones.
 * Fabricante.
 * Precio.

Esta informaci칩n ser치 guardada en la BBDD y se colocar치 al producto en estado `DISPONIBLE`.

El diagrama de secuencias para la presente historia es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Administrador 

Administrador -> BOT: Solicitar registro de producto en el sistema
BOT -> Administrador: Notificaci칩n de registro de nuevo producto

@enduml
....

#### Escenarios
1. Registro CORRECTO.
2. Registro INCORRECTO.
3. Validaci칩n de datos ingresados por el administrador.

#### Casos de Prueba

*101.1.1 Validaci칩n de par치metros* 
Descripci칩n: Al momento de registrarse el nuevo producto, los siguientes campos son obligatorios: Nombre del producto, categor칤a, c칩digo, foto del producto, cantidad disponible, fabricante y precio.

En caso de que el `Administrador no ingrese uno de estos valores` no se debe proceder a registrar el producto.

Pasos:

 1. El `Administrador` env칤a el comando `/registrar`
    - Datos: comando `/registrar`
    - Resultado: El BOT pregunta por el nombre del producto
 2. El `Administrador` coloca un espacio en blanco
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el nombre del producto porque no puede haber espacios en blanco.
 3. El `Administrador` coloca car치cteres no convencionales como emojis.
    - Datos: Coloca `Pintura-Roja游꿛`
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.
