= {product} - Hist칩rias de Usuario
Universidad Cat칩lica Boliviana San Pablo - Regional La Paz. <teddy.aruquipa@ucb.edu.bo>
1.0.0
:product: BOT Empresa Metal Corp.

## Introducci칩n
El present칠 documento presenta el detalle de todas las histor칤as de usuario necesarias para la construcci칩n de un BOT en la plataforma de Telegram, el cu치l estar치 dirigido para la empresa Metal Corp.

Se ha establecido que la funcionalidad m칤nima para la implementaci칩n ser치 la siguiente:

Para los clientes:

 1. Los clientes pueden ver informaci칩n de la empresa, como ser las sucursales disponibles, direcciones y horarios.
 2. Los clientes pueden consultar los productos disponibles mediante el BOT, asi como tambien la sucursal en la que se encuentran.
 3. Los clientes pueden realizar una reserva de producto para recogerlo posteriormente.

Para el personal de la empresa:

 1. El personal de la empresa debe poder aprobar o negar las reservas de productos.
 2. El personal puede consultar un producto de otra sucursal diferente a la suya.
 3. El personal de la empresa podra a침adir o eliminar productos.

Para el Administrador de la empresa:

 1. El administrador de la empresa debe poder registrar y actualizar los productos.

## Hist칩rias de Usuario.

### 100 - Solicitud de reserva de productos.

*Autor*: Gutber Blanco Gomez

*Fecha*: 01/03/2022

*Prioridad*: ALTA

#### Descripci칩n
Un `Cliente` el cual est치 habilitado para reservas (Hist칩rias de usuario No 090) debe solicitar la reserva de productos por medio del chatbot, para esto debe especificar el o los productos que desea adquirir, asi como el d칤a en el que se recoger치 la mercader칤a, el cual no podra exceder los 7 dias a partir de la solicitud. Una vez enviada la solicitud el `Personal de Metal Corp.` proceder치 a aprobar o negar la solicitud de reserva del cliente, en caso de que la `Solicitud` sea negada se debe agregar un detalle del porqu칠 se neg칩 dicha reserva. Caso contrario se le notificar치 al cliente que la solicitud fue aprobada. Adem치s el `BOT` debe llevar un control de:

 * El stock de los productos
 * El registro de reservas realizadas (La reserva solo se puede cancelar 48 horas antes de  la fecha de entrega)
 * El tiempo de duraci칩n de la reserva (La reserva durara un m치ximo de 2 dias despu칠s de la fecha de entrega)

La solicitud pasar치 pos los siguientes estados:

  * *SOLICITADO*: Cuando el cliente env칤a su solicitud de reserva al BOT y el BOT no la rechaza.
  * *NO V츼LIDO*: Cuando el cliente env칤a su solicitud de reserva al BOT e ingresa una cantidad mayor al stock disponible del producto seleccionado o menor a 1.
  * *APROBADO*: Solicitud de reserva aprobada por el personal de Metal Corp.
  * *RECHAZADO*: Solicitud de reserva negada por el personal de Metal Corp.
  * *CANCELADA*: El cliente cancel칩 una solicitud de reserva APROBADA

El diagrama de estados para la `SOLICITUD` ser치:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> CANCELADO
APROBADO --> [*]
CANCELADO --> [*]

@enduml
....

#### Escenarios
1. El producto no est치 registrado en la Base de Datos.
2. Validaci칩n de la cantidad.
3. El cliente no esta habilitado para reservas.
4. Seleccionar productos.
5. El cliente solicita una reserva.
6. El cliente cancela una reserva.
7. El producto est치 registrado en la aplicaci칩n con stock insuficiente.
8. El personal rechaza una solicitud de reserva.


#### Casos de Prueba
*100.1.1 El producto no se encuentra*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot pedir치 el nombre o c칩digo del producto.

En caso de que el `cliente ingrese mal el parametro o no exista el producto` no se debe proceder a reservar el producto.

Pasos:

1. El `Cliente` env칤a el comando `/reservar`
- Datos: comando `/reservar`
- Resultado: El BOT pide el nombre o c칩digo del producto
2. El `Cliente` ingresa caracteres especiales.
- Datos: Ingresa `Pintura Rojos 游$`
- Resultado: El BOT indica que no puede colocar caracteres especiales
3. El `Cliente` ingresa un producto inexistente.
- Datos: Ingresa `Llantas`
- Resultado: El BOT le indica que el producto no existe en la tienda.

*100.1.2 Validaci칩n de la cantidad*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot pedir치 una cantidad el cual debe ser ingresado por el cliente.

En caso de que el `cliente ingrese una cantidad erronea` no se debe proceder a registrar el producto.

Pasos:

1. El `Cliente` env칤a el comando `/realizar_reserva`.
- Datos: comando `/realizar_reserva`
- Resultado: El BOT pregunta por la cantidad que requiere.
2. El `Cliente` ingresa el n칰mero 0.
- Datos: Ingresa `0`
- Resultado: El BOT indica que el n칰mero no puede ser 0 o negativo
3. El `Cliente` coloca una cantidad mayor al stock.
- Datos: Ingresa `Cantidad mayor al stock`
- Resultado: El BOT le indica que la cantidad no puede superar al stock.

*100.1.3 El cliente no est치 habilitado para reservas*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot verificar치 que el cliente este habilitado(Ver Historia 090) para realizar dicha reserva.

En caso de que el `cliente no se encuentre habilitado` no se proceder치 a realizar la reserva.

Pasos:

1. El `Cliente` env칤a el comando `/reservar`
- Datos: comando `/reservar`
- Resultado: El BOT le notificar치 que su usuario no esta habilitado y le mandara pasos para su habilitaci칩n.

*100.1.4 El cliente solicita una reserva*
Descripci칩n: Una vez terminado la etapa de selecci칩n de productos, el `Cliente` podr치 confirmar la reserva y el bot enviar치 la solicitud.

Pasos:

1. El `Cliente` env칤a el comando `/confirmar_reserva`.
- Datos: comando `/confirmar_reserva`
- Resultado: El BOT le notifica que la solicitud fue enviada y que espere una respuesta en un tiempo predeterminado.


### 101 - Registro de producto en el sistema.

*Autor*: Teddy Aruquipa Peralta

*Fecha*: 03/03/2022

*Prioridad*: ALTA

#### Descripci칩n

El `Administrador de Metal Corp.` debe poder realizar el registro de nuevos productos en el sistema por medio del mismo BOT, al momento de solicitar su registro, el Administrador deber치 enviar la siguiente informaci칩n:

 * Nombre del producto.
 * Categor칤a.
 * C칩digo.
 * Foto del producto.
 * Cantidad disponible.
 * Dimensiones.
 * Fabricante.
 * Precio.

Esta informaci칩n ser치 guardada en la BBDD y se colocar치 al producto en estado `DISPONIBLE`.

El diagrama de secuencias para la presente historia es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Administrador 

Administrador -> BOT: Solicitar registro de producto en el sistema
BOT -> Administrador: Notificaci칩n de registro de nuevo producto

@enduml
....

#### Escenarios
1. Registro CORRECTO.
2. Registro INCORRECTO.
3. Validaci칩n de datos ingresados por el administrador.

#### Casos de Prueba

*101.1.1 Validaci칩n de par치metros* 
Descripci칩n: Al momento de registrarse el nuevo producto, los siguientes campos son obligatorios: Nombre del producto, categor칤a, c칩digo, foto del producto, cantidad disponible, fabricante y precio.

En caso de que el `Administrador no ingrese uno de estos valores` no se debe proceder a registrar el producto.

Pasos:

 1. El `Administrador` env칤a el comando `/registrar`
    - Datos: comando `/registrar`
    - Resultado: El BOT pregunta por el nombre del producto
 2. El `Administrador` coloca un espacio en blanco
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el nombre del producto porque no puede haber espacios en blanco.
 3. El `Administrador` coloca car치cteres no convencionales como emojis.
    - Datos: Coloca `Pintura-Roja游꿛`
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.