= {product} - Hist贸rias de Usuario
Universidad Cat贸lica Boliviana. <teddy.aruquipa@ucb.edu.bo>
1.0.0
:product: BOT Empresa Metal Corp.

## Introducci贸n
El presento documente tendr谩 el detalle de todas las histor铆as de usuario para la construcci贸n de un BOT en la plataforma
Telegram, el cual dispondra de diferentes funcionalidades, para asi apoyar a la venta de productos de la empresa Metal Corp.

Se ha establecido que la funcionalidad m铆nima para la implementaci贸n ser谩:

Para los clientes:

 1. Los clientes pueden ver informacion de la empresa, como ser las sucursales disponibles.
 2. Los clientes pueden consultar los productos disponibles mediante el BOT.
 3. Los clientes pueden realizar una reserva de producto para recogerlo posteriormente.

Para el personal de la empresa:

 1. El personal de la empresa debe poder aprobar o negar las reservas de productos.

Para el Administrador de la empresa:

 1. El administrador de la empresa debe poder registrar y actualizar los productos.

## Hist贸rias de Usuario.

### 100 - Solicitud de reserva de productos.

*Autores*: Gutber Blanco - Teddy Aruquipa Peralta

*Fecha*: 01/03/2022

*Prioridad*: ALTA

#### Descripci贸n
Un `Cliente` debe solicitar la reserva de productos por medio de la aplicaci贸n, para esto debe especificar el o los productos que desea adquirir, asi como el horario en el que se recogera la mercaderia. Una vez enviada su solicitud el `Personal de Metal Corp.` proceder谩 a aprobar o negar la solicitud de reserva del cliente, en caso de que la `Solicitud` sea negada se debe agregar un detalle del porque se nego dicha reserva. Adem谩s el `BOT` debe llevar un control de:
 * El stock de los productos
 * El registro de reservas realizadas
 * El tiempo de duracion de la reserva

La solicitud pasar谩 pos los siguientes estados:

  * *SOLICITADO*: Cuando el cliente env铆a su solicitud de reserva al BOT y el BOT no la rechaza.
  * *NO VLIDO*: Cuando el cliente env铆a su solicitud de reserva al BOT e ingresa una cantidad mayor al stock disponible del producto seleccionado.
  * *APROBADO*: Solicitud de reserva aprobada por el personal de Metal Corp.
  * *RECHAZADO*: Solicitud de reserva negadda por el personal de Metal Corp.
  * *CANCELADA*: El cliente cancel贸 una solicitud de reserva APROBADA

El diagrama de estados para la `SOLICITUD` ser谩:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> CANCELADO
APROBADO --> [*]
CANCELADO --> [*]

@enduml
....

#### Escenarios
1. El producto no esta registrado en la aplicaci贸n.
2. El producto esta registrado en la aplicaci贸n con stock suficiente.
3. El producto esta registrado en la aplicaci贸n con stock insuficiente.
4. Solicitud de reserva.
5. Cancelaci贸n de reserva.

### 101 - Registro de producto en el sistema.

*Autores*: Gutber Blanco - Teddy Aruquipa Peralta

*Fecha*: 03/03/2022

*Prioridad*: ALTA

#### Descripci贸n

El `Administrador de Metal Corp.` debe poder realizar el registro de nuevos productos en el sistema por medio del mismo BOT, al momento de solicitar su registro, el empleado deber谩 enviar la siguiente informaci贸n:

 * Nombre del producto.
 * Categor铆a.
 * C贸digo.
 * Foto del producto.
 * Cantidad disponible.
 * Dimensiones.
 * Fabricante.
 * Precio.

Esta informaci贸n sera guardada en la BBDD y se colocara al producto en estado `DISPONIBLE`.

El diagrama de secuencias para la presente hist贸ria es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Administrador 

Administrador -> BOT: Solicitar registro de producto en el sistema
BOT -> Administrador: Notificaci贸n de registro de nuevo producto

@enduml
....

#### Escenarios
1. Registro CORRECTO.
2. Registro INCORRECTO.
3. Validaci贸n de datos ingresados por el administrador.

#### Casos de Prueba

*101.1.1 Validaci贸n de par谩metros* 
Descripci贸n: Al momento de registrarse el nuevo producto, los siguientes campos son obligatorios: Nombre del producto, categor铆a,c贸digo, foto del producto, cantidad disponible, fabricante y precio.

En caso de que el `Administrador no ingrese uno de estos valores` no se debe proceder a registrar el producto.

Pasos:

 1. El `Administrador` env铆a el comando `/registrar`
    - Datos: comando `/registrar`
    - Resultado: El BOT pregunta por el nombre del producto
 2. El `Administrador` coloca un espacio en blanco
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el nombre del producto porque no puede ser espacios en blanco.
 3. El `Administrador` coloca car谩cteres no convencionales como emojis.
    - Datos: Coloca `Pintura-Roja`
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.
