= {product} - Hist칩rias de Usuario
Universidad Cat칩lica Boliviana San Pablo - Regional La Paz. <teddy.aruquipa@ucb.edu.bo>
1.0.0
:product: BOT Empresa Metal Corp.

## Introducci칩n
El present칠 documento presenta el detalle de todas las histor칤as de usuario necesarias para la construcci칩n de un BOT en la plataforma de Telegram, el cu치l estar치 dirigido para la empresa Metal Corp, la cual tiene como principal actividad la venta de productos de construcci칩n.

Se ha establecido que la funcionalidad m칤nima para la implementaci칩n ser치 la siguiente:

Para los clientes:

 1. Los clientes pueden ver informaci칩n de la empresa, como ser las sucursales disponibles, direcciones y horarios.
 2. Los clientes pueden consultar los productos disponibles mediante el BOT, asi como tambien la sucursal en la que se encuentran.
 3. Los clientes pueden realizar una reserva de producto para recogerlo posteriormente.

Para el personal de la empresa:

 1. El personal de la empresa debe poder aprobar o negar las reservas de productos.
 2. El personal puede consultar un producto de otra sucursal diferente a la suya.
 3. El personal de la empresa podra a침adir o eliminar productos.

Para el Administrador de la empresa:

 1. El administrador de la empresa debe poder registrar y actualizar los productos.

## Hist칩rias de Usuario.

### 100 - Solicitud de reserva de productos.

*Autor*: Gutber Blanco Gomez

*Fecha*: 08/03/2022

*Prioridad*: ALTA

#### Descripci칩n
Un `Cliente` el cual est치 habilitado para reservas (Hist칩rias de usuario No 090) debe solicitar la reserva de productos por medio del chatbot, para esto debe especificar el o los productos que desea adquirir, asi como el d칤a en el que se recoger치 la mercader칤a, el cual no podr치 exceder los 7 dias a partir de la solicitud. Una vez enviada la solicitud el `Personal de Metal Corp.` proceder치 a aprobar o negar la solicitud de reserva del cliente, en caso de que la `Solicitud` sea negada se debe agregar un detalle del porqu칠 se neg칩 dicha reserva. Caso contrario el `BOT` notificar치 al cliente que la solicitud fue aprobada. Adem치s el `BOT` debe llevar un control de:

 * El stock de los productos
 * El registro de reservas realizadas (La reserva solo se puede cancelar 48 horas antes de  la fecha de entrega)
 * El tiempo de duraci칩n de la reserva (La reserva durara un m치ximo de 2 dias despu칠s de la fecha de entrega)

La solicitud pasar치 pos los siguientes estados:

  * *SOLICITADO*: Cuando el cliente env칤a su solicitud de reserva al BOT y el BOT no la rechaza.
  * *NO V츼LIDO*: Cuando el cliente env칤a su solicitud de reserva al BOT e ingresa una cantidad mayor al stock disponible del producto seleccionado o menor a 1.
  * *APROBADO*: Solicitud de reserva aprobada por el personal de Metal Corp.
  * *RECHAZADO*: Solicitud de reserva negada por el personal de Metal Corp.
  * *CANCELADA*: El cliente cancel칩 una solicitud de reserva APROBADA

El diagrama de estados para la `SOLICITUD` ser치:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> CANCELADO
APROBADO --> [*]
CANCELADO --> [*]

@enduml
....

#### Escenarios
1. El producto no est치 registrado en la Base de Datos.
2. Validaci칩n de la cantidad.
3. El cliente no esta habilitado para reservas.
4. Seleccionar productos.
5. El cliente solicita una reserva.
6. El cliente cancela una reserva.
7. El personal rechaza una solicitud de reserva.
8. El personal acepta una solicitud de reserva.


#### Casos de Prueba
*100.1.1 El producto no se encuentra*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot pedir치 el nombre o c칩digo del producto.

En caso de que el `cliente ingrese mal el parametro o no exista el producto` no se debe proceder a reservar el producto.

Pasos:

1. El `Cliente` env칤a el comando `/reservar`
- Datos: comando `/reservar`
- Resultado: El BOT pide el nombre o c칩digo del producto
2. El `Cliente` ingresa caracteres especiales.
- Datos: Ingresa `Pintura Roja游꿛 `
- Resultado: El BOT indica que no puede colocar caracteres especiales
3. El `Cliente` ingresa un producto inexistente.
- Datos: Ingresa `Llantas`
- Resultado: El BOT le indica que el producto no existe en la tienda.

*100.1.2 Validaci칩n de la cantidad*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot pedir치 una cantidad el cual debe ser ingresado por el cliente.

En caso de que el `cliente ingrese una cantidad err칩nea` no se debe proceder a registrar el producto.

Pasos:

1. El `Cliente` env칤a el comando `/realizar_reserva`.
- Datos: comando `/realizar_reserva`
- Resultado: El BOT pregunta por la cantidad que requiere.
2. El `Cliente` ingresa el n칰mero 0.
- Datos: Ingresa `0`
- Resultado: El BOT indica que el n칰mero no puede ser 0 o negativo
3. El `Cliente` coloca una cantidad mayor al stock.
- Datos: Ingresa `Cantidad mayor al stock`
- Resultado: El BOT le indica que la cantidad no puede superar al stock y le muestra el stock.
4. El `Cliente` coloca una cantidad con decimales.
- Datos: Ingresa `Cantidad con decimales`
- Resultado: El BOT le indica que la cantidad no debe contener decimales, solo pueden ser numeros enteros.



*100.1.3 El cliente no est치 habilitado para reservas*
Descripci칩n: Al momento de realizar la reserva de un producto, el bot verificar치 que el cliente este habilitado(Ver Historia 090) para realizar dicha reserva.

En caso de que el `cliente no se encuentre habilitado` no se proceder치 a realizar la reserva.

Pasos:

1. El `Cliente` env칤a el comando `/reservar`
- Datos: comando `/reservar`
- Resultado: El BOT le notificar치 que su usuario no esta habilitado y le mandara pasos para su habilitaci칩n.

*100.1.4 Selecci칩n de productos*
Descripci칩n: Para poder solicitar una reserva el `cliente` debera seleccionar primero sus productos mediante una b칰squeda del producto (Ver historia 105).

Pasos:

1. El `Cliente` env칤a el comando `/reservar`.
- Datos: comando `/reservar`
- Resultado: El BOT pide el nombre o c칩digo del producto
2. El `Cliente` ingresa `Aluminio 4mm`.
- Datos: Ingresa `Aluminio 4mm`
- Resultado: El BOT muestra una lista de productos coincidentes con la b칰squeda y pide seleccionar una opci칩n (Ver Ejemplo 100.1).
3. El `Cliente` selecciona una opci칩n.
- Datos: El cliente selecciona una opci칩n.
- Resultado: El BOT le muestra los detalles del producto y pide confirmar la reserva
4. El `Cliente` env칤a comando `/realizar_reserva`.
- Datos: comando `/realizar_reserva`
- Resultado: El Bot pregunta por la cantidad que requiere. (Ver Caso de prueba 100.1.2)


*100.1.5 El cliente solicita una reserva*
Descripci칩n: Una vez terminado la etapa de selecci칩n de productos, el `Cliente` podr치 confirmar la reserva y el bot le pedir치 una fecha con formato dd-mm-aaaa y no superior a 7 dias a partir de la fecha actual. Si el `cliente` no sigue el formato no se debera proceder a reservar el producto, caso contrario se le notificara que la solicitud de reserva fue enviada.

Pasos:

1. El `Cliente` env칤a el comando `/confirmar_reserva`.
- Datos: comando `/confirmar_reserva`
- Resultado: El BOT pedir치 que ingrese una fecha en el formato dd-mm-aaaa.
2. El `Cliente` ingresa la fecha `05/06/2022`
- Datos: Cliente ingresa `05/06/2022`
- Resultado: El BOT le notifica que el formato es incorrecto.
3. El `Cliente` ingresa una fecha fuera del rango.
- Datos: Cliente ingresa fecha fuera del rango.
- Resultado: El BOT le notificar치 que la fecha no puede superar los 7 dias.
4: El `Cliente` ingresa `12-03-2022`.
- Datos: Cliente ingresa `12-03-2022`
- Resultado: El BOT le notifica que la solicitud fue enviada.

*100.1.6 El cliente cancela una reserva*
Descripci칩n: Una vez aceptada una solicitud de reserva (Ver Caso de prueba ), el cliente podr치 realizar la cancelaci칩n de la reserva siempre y cuando este dentro del tiempo permitido(d칤a del pedido hasta 48 horas antes de la fecha de entrega), caso contrario el `Bot` le notificara que ya no puede cancelar la reserva.

Pasos:

1. El `Cliente` env칤a el comando `/cancelar_reserva`.
- Datos: comando `/cancelar_reserva`
- Resultado: Si est치 dentro del tiempo permitido el `Bot` le notificara que la reserva fue cancelada, caso contrario le notificara que no se puede realizar la cancelaci칩n.

*100.1.7 El personal rechaza una solicitud de reserva*
Descripci칩n: Cuando un `cliente` env칤a una solicitud de reserva, el `Bot` enviara la solicitud al `personal` de la empresa, si el personal de la empresa decide rechazar la solicitud, se deber치 explicar el motivo del rechazo de la solicitud, el cual ha de ser enviado al `Cliente`.

Pasos:

1. El `Personal` recibe una solicitud de reserva.
2. El `Personal` ve la solicitud y env칤a el comando `/rechazar_reserva`.
- Datos: comando `/rechazar_reserva`
- Resultado: El BOT pedir치 el motivo del rechazo de la solicitud.
3. El `Personal` ingresa el motivo del rechazo de la solicitud.
- Datos: `Personal` env칤a motivo del rechazo.
- Resultado: El BOT recibe el motivo y lo env칤a al `Cliente` que hizo la reserva.

*100.1.8 El personal acepta una solicitud de reserva*
Descripci칩n: Cuando un `cliente` env칤a una solicitud de reserva, el `Bot` enviara la solicitud al `personal` de la empresa, si el personal de la empresa decide aceptar la solicitud, el `BOT` debera enviar una notificaci칩n al `cliente` que realizo el pedido, adem치s se debera enviar un recordatorio cada dia desde el dia en que se acept칩 la solicitud hasta 2 dias despu칠s de la fecha de entrega.

Pasos:

1. El `Personal` recibe una solicitud de reserva.
2. El `Personal` ve la solicitud y env칤a el comando `/aceptar_reserva`.
- Datos: comando `/aceptar_reserva`
- Resultado: El BOT notificara al usuario la aceptaci칩n de la reserva y se le enviara un recordatorio cada dia hasta 2 dias despu칠s de la fecha de entrega.

#### Ejemplos.
*Ejemplo 100.1:*
```
Cliente: /reservar
Bot: Por favor ingr칠se el nombre o c칩digo del producto ha reservar
Cliente: Aluminio 3mm
Bot: Se encontraron los siguientes productos, por favor seleccione una opci칩n:
     1. Aluminio 3mm Rectangular
     2. Aluminio 3mm Barra
     3. Aluminio Reforzado 3mm
     4. Buscar otro producto
Cliente: 2
Bot: Aluminio 3mm Barra
     Unidad: Metro
     Precio: 35Bs.
     Cantidad disponible: 15
     Detalle: Aluminio 3mm Barra, marca strato
     Desea realizar la reserva?
Cliente: /realizar_reserva
Bot: Por favor, ingrese la cantidad a reservar:
Cliente: 7
Bot: Desea agregar otro producto?
     1. Si
     2. No
Cliente: 2
Bot: Aluminio 3mm Barra cant. 15
     Desea confirmar la reserva?
Cliente: /Confirmar_reserva
Bot: Por favor, ingrese la fecha para el recojo del producto.
     (Ingrese la fecha en el formato dd-mm-aaaa)
Cliente: 12-03-2022
Bot: La solicitud de reserva fue enviada, por favor espere un momento.
(Ver Ejemplo 100.2)
Bot: La solicitud de reserva fue aprobada.
     No Reserva: 1420
     Producto: Aluminio 3mm Barra (Cod: 1503)
     Cantidad: 15
     Fecha de entrega: 12-03-2022
```
*Ejemplo 100.2:*
```
Bot: Tiene una solitud de reserva.
     No Reserva: 1420
     Producto: Aluminio 3mm Barra (Cod: 1503)
     Cantidad: 15
     Fecha de entrega: 12-03-2022
     Desea aceptar la reserva?
Personal: /Aceptar_reserva
Bot: Se le notificara al cliente el estado de la reserva.
```


### 101 - Registro de producto en el sistema.

*Autor*: Teddy Aruquipa Peralta

*Fecha*: 03/03/2022

*Prioridad*: ALTA

#### Descripci칩n

El `Administrador de Metal Corp.` debe poder realizar el registro de nuevos productos en el sistema por medio del mismo BOT, al momento de solicitar su registro, el Administrador deber치 enviar la siguiente informaci칩n:

 * Nombre del producto.
 * Categor칤a.
 * C칩digo.
 * Foto del producto.
 * Cantidad disponible.
 * Dimensiones.
 * Fabricante.
 * Precio.

Esta informaci칩n ser치 guardada en la BBDD y se colocar치 al producto en estado `DISPONIBLE`.

El diagrama de secuencias para la presente historia es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Administrador 

Administrador -> BOT: Solicitar registro de producto en el sistema
BOT -> Administrador: Notificaci칩n de registro de nuevo producto

@enduml
....

#### Escenarios
1. Registro CORRECTO.
2. Registro INCORRECTO.
3. Validaci칩n de parametros ingresados por el administrador.

#### Casos de Prueba

*101.1.1 Verificaci칩n de parametros*
Descripci칩n: Al momento de realizar el registro de un producto, el bot pedir치 una cantidad de parametros, los cuales deben ser ingresados por el administrador.

En caso de que el `administrador ingrese un dato en el formato err칩neo o que omita un dato` no se debe proceder a registrar el producto.

Pasos:

1. El `Administrador` env칤a el comando `/registrar_producto`.
- Datos: comando `/registrar_producto`
- Resultado: El BOT verifica los parametros ingresados.
2. El `Administrador` ingresa una letra en el PRECIO.
- Datos: Ingresa `78a.50`
- Resultado: El BOT indica que el precio no puede contener letras.
3. El `Administrador` no coloca la imagen del producto.
- Datos: Imagen, no ingresada
- Resultado: El BOT le indica que es obligatorio ingresar una imagen de referencia del producto.

*101.1.2 Validaci칩n de par치metros* 
Descripci칩n: Al momento de registrarse el nuevo producto, los siguientes campos son obligatorios: Nombre del producto, categor칤a, c칩digo, foto del producto, cantidad disponible, fabricante y precio.

En caso de que el `Administrador no ingrese uno de estos valores` no se debe proceder a registrar el producto.

Pasos:

 1. El `Administrador` env칤a el comando `/registrar`
    - Datos: comando `/registrar`
    - Resultado: El BOT pregunta por el nombre del producto
 2. El `Administrador` coloca un espacio en blanco
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el nombre del producto porque no puede haber espacios en blanco.
 3. El `Administrador` coloca car치cteres no convencionales como emojis.
    - Datos: Coloca `Pintura-Roja游꿛`
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.